namespace mk152
{
	// Token: 0x0200000A RID: 10
	internal partial class Univac1219 : global::System.Windows.Forms.Form
	{
		// Token: 0x06000027 RID: 39 RVA: 0x0014ACF8 File Offset: 0x001490F8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool Disposing)
		{
			if (Disposing)
			{
				bool flag = this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			base.Dispose(Disposing);
		}

		// Token: 0x06000060 RID: 96 RVA: 0x0014B824 File Offset: 0x00149C24
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::mk152.Univac1219));
			this.BUTTON_LOAD = new global::System.Windows.Forms.Button();
			this.Button_DIS_P = new global::System.Windows.Forms.Button();
			this.Frame2 = new global::System.Windows.Forms.GroupBox();
			this.SKIP4 = new global::System.Windows.Forms.Button();
			this.SKIP3 = new global::System.Windows.Forms.Button();
			this.SKIP2 = new global::System.Windows.Forms.Button();
			this.SKIP1 = new global::System.Windows.Forms.Button();
			this.SKIP0 = new global::System.Windows.Forms.Button();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.START = new global::System.Windows.Forms.Button();
			this.BUTTON_FII = new global::System.Windows.Forms.Button();
			this.REG_FUNC = new global::System.Windows.Forms.TextBox();
			this.SWITCH_FUNC = new global::System.Windows.Forms.Button();
			this.Stop_Renamed = new global::System.Windows.Forms.Button();
			this.REG_SR = new global::System.Windows.Forms.TextBox();
			this.REG_AU = new global::System.Windows.Forms.TextBox();
			this.REG_ICR = new global::System.Windows.Forms.TextBox();
			this.REG_PROG = new global::System.Windows.Forms.TextBox();
			this.REG_AL = new global::System.Windows.Forms.TextBox();
			this.SWITCH_CLEAR = new global::System.Windows.Forms.Button();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.FII = new global::System.Windows.Forms.Label();
			this._Label3_2 = new global::System.Windows.Forms.Label();
			this._Label3_1 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this._Label3_0 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.STOPS = new global::System.Windows.Forms.GroupBox();
			this.STOP4 = new global::System.Windows.Forms.Button();
			this.STOP3 = new global::System.Windows.Forms.Button();
			this.STOP2 = new global::System.Windows.Forms.Button();
			this.STOP1 = new global::System.Windows.Forms.Button();
			this.STOP0 = new global::System.Windows.Forms.Button();
			this.SWITCH_MODE = new global::System.Windows.Forms.Button();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.Timer2 = new global::System.Windows.Forms.Timer(this.components);
			this.Label3 = new global::System.Windows.Forms.Label();
			this.INS_SECOND = new global::System.Windows.Forms.TextBox();
			this.Frame2.SuspendLayout();
			this.STOPS.SuspendLayout();
			this.SuspendLayout();
			this.BUTTON_LOAD.BackColor = global::System.Drawing.SystemColors.Control;
			this.BUTTON_LOAD.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.BUTTON_LOAD.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.BUTTON_LOAD.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control button_LOAD = this.BUTTON_LOAD;
			global::System.Drawing.Point point = new global::System.Drawing.Point(131, 376);
			button_LOAD.Location = point;
			this.BUTTON_LOAD.Name = "BUTTON_LOAD";
			this.BUTTON_LOAD.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control button_LOAD2 = this.BUTTON_LOAD;
			global::System.Drawing.Size size = new global::System.Drawing.Size(49, 33);
			button_LOAD2.Size = size;
			this.BUTTON_LOAD.TabIndex = 36;
			this.BUTTON_LOAD.Text = "Load";
			this.BUTTON_LOAD.UseVisualStyleBackColor = false;
			this.Button_DIS_P.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.Button_DIS_P.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button_DIS_P.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button_DIS_P.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control button_DIS_P = this.Button_DIS_P;
			point = new global::System.Drawing.Point(72, 376);
			button_DIS_P.Location = point;
			this.Button_DIS_P.Name = "Button_DIS_P";
			this.Button_DIS_P.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control button_DIS_P2 = this.Button_DIS_P;
			size = new global::System.Drawing.Size(49, 33);
			button_DIS_P2.Size = size;
			this.Button_DIS_P.TabIndex = 35;
			this.Button_DIS_P.Text = "Disc Adv P";
			this.Button_DIS_P.UseCompatibleTextRendering = true;
			this.Button_DIS_P.UseVisualStyleBackColor = false;
			this.Frame2.BackColor = global::System.Drawing.Color.Black;
			this.Frame2.Controls.Add(this.SKIP4);
			this.Frame2.Controls.Add(this.SKIP3);
			this.Frame2.Controls.Add(this.SKIP2);
			this.Frame2.Controls.Add(this.SKIP1);
			this.Frame2.Controls.Add(this.SKIP0);
			this.Frame2.Controls.Add(this.Label6);
			this.Frame2.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Frame2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control frame = this.Frame2;
			point = new global::System.Drawing.Point(32, 527);
			frame.Location = point;
			this.Frame2.Name = "Frame2";
			global::System.Windows.Forms.Control frame2 = this.Frame2;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(0);
			frame2.Padding = padding;
			this.Frame2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control frame3 = this.Frame2;
			size = new global::System.Drawing.Size(217, 63);
			frame3.Size = size;
			this.Frame2.TabIndex = 18;
			this.Frame2.TabStop = false;
			this.SKIP4.BackColor = global::System.Drawing.Color.LightGray;
			this.SKIP4.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.SKIP4.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SKIP4.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control skip = this.SKIP4;
			point = new global::System.Drawing.Point(20, 33);
			skip.Location = point;
			this.SKIP4.Name = "SKIP4";
			this.SKIP4.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control skip2 = this.SKIP4;
			size = new global::System.Drawing.Size(25, 21);
			skip2.Size = size;
			this.SKIP4.TabIndex = 23;
			this.SKIP4.Text = "4";
			this.SKIP4.UseVisualStyleBackColor = false;
			this.SKIP3.BackColor = global::System.Drawing.Color.LightGray;
			this.SKIP3.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.SKIP3.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SKIP3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control skip3 = this.SKIP3;
			point = new global::System.Drawing.Point(59, 33);
			skip3.Location = point;
			this.SKIP3.Name = "SKIP3";
			this.SKIP3.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control skip4 = this.SKIP3;
			size = new global::System.Drawing.Size(25, 21);
			skip4.Size = size;
			this.SKIP3.TabIndex = 22;
			this.SKIP3.Text = "3";
			this.SKIP3.UseVisualStyleBackColor = false;
			this.SKIP2.BackColor = global::System.Drawing.Color.LightGray;
			this.SKIP2.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.SKIP2.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SKIP2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control skip5 = this.SKIP2;
			point = new global::System.Drawing.Point(99, 33);
			skip5.Location = point;
			this.SKIP2.Name = "SKIP2";
			this.SKIP2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control skip6 = this.SKIP2;
			size = new global::System.Drawing.Size(25, 21);
			skip6.Size = size;
			this.SKIP2.TabIndex = 21;
			this.SKIP2.Text = "2";
			this.SKIP2.UseVisualStyleBackColor = false;
			this.SKIP1.BackColor = global::System.Drawing.Color.LightGray;
			this.SKIP1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.SKIP1.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SKIP1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control skip7 = this.SKIP1;
			point = new global::System.Drawing.Point(136, 33);
			skip7.Location = point;
			this.SKIP1.Name = "SKIP1";
			this.SKIP1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control skip8 = this.SKIP1;
			size = new global::System.Drawing.Size(25, 21);
			skip8.Size = size;
			this.SKIP1.TabIndex = 20;
			this.SKIP1.Text = "1";
			this.SKIP1.UseVisualStyleBackColor = false;
			this.SKIP0.BackColor = global::System.Drawing.Color.LightGray;
			this.SKIP0.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.SKIP0.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SKIP0.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control skip9 = this.SKIP0;
			point = new global::System.Drawing.Point(174, 33);
			skip9.Location = point;
			this.SKIP0.Name = "SKIP0";
			this.SKIP0.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control skip10 = this.SKIP0;
			size = new global::System.Drawing.Size(25, 21);
			skip10.Size = size;
			this.SKIP0.TabIndex = 19;
			this.SKIP0.Text = "0";
			this.SKIP0.UseVisualStyleBackColor = false;
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Black;
			this.Label6.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label6.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label = this.Label6;
			point = new global::System.Drawing.Point(80, 13);
			label.Location = point;
			this.Label6.Name = "Label6";
			this.Label6.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control label2 = this.Label6;
			size = new global::System.Drawing.Size(63, 16);
			label2.Size = size;
			this.Label6.TabIndex = 34;
			this.Label6.Text = "S K I P S";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.START.BackColor = global::System.Drawing.SystemColors.Control;
			this.START.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.START.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.START.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control start = this.START;
			point = new global::System.Drawing.Point(238, 376);
			start.Location = point;
			this.START.Name = "START";
			this.START.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control start2 = this.START;
			size = new global::System.Drawing.Size(49, 33);
			start2.Size = size;
			this.START.TabIndex = 17;
			this.START.Text = "Start";
			this.START.UseVisualStyleBackColor = false;
			this.BUTTON_FII.BackColor = global::System.Drawing.Color.Black;
			this.BUTTON_FII.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.BUTTON_FII.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.BUTTON_FII.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control button_FII = this.BUTTON_FII;
			point = new global::System.Drawing.Point(115, 201);
			button_FII.Location = point;
			this.BUTTON_FII.Name = "BUTTON_FII";
			this.BUTTON_FII.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control button_FII2 = this.BUTTON_FII;
			size = new global::System.Drawing.Size(32, 23);
			button_FII2.Size = size;
			this.BUTTON_FII.TabIndex = 15;
			this.BUTTON_FII.Text = "50";
			this.BUTTON_FII.UseVisualStyleBackColor = false;
			this.REG_FUNC.AcceptsReturn = true;
			this.REG_FUNC.BackColor = global::System.Drawing.Color.Black;
			this.REG_FUNC.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.REG_FUNC.Font = new global::System.Drawing.Font("Arial", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.REG_FUNC.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			global::System.Windows.Forms.Control reg_FUNC = this.REG_FUNC;
			point = new global::System.Drawing.Point(168, 194);
			reg_FUNC.Location = point;
			this.REG_FUNC.MaxLength = 0;
			this.REG_FUNC.Name = "REG_FUNC";
			this.REG_FUNC.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control reg_FUNC2 = this.REG_FUNC;
			size = new global::System.Drawing.Size(49, 35);
			reg_FUNC2.Size = size;
			this.REG_FUNC.TabIndex = 13;
			this.REG_FUNC.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.SWITCH_FUNC.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.SWITCH_FUNC.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.SWITCH_FUNC.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SWITCH_FUNC.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control switch_FUNC = this.SWITCH_FUNC;
			point = new global::System.Drawing.Point(12, 376);
			switch_FUNC.Location = point;
			this.SWITCH_FUNC.Name = "SWITCH_FUNC";
			this.SWITCH_FUNC.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control switch_FUNC2 = this.SWITCH_FUNC;
			size = new global::System.Drawing.Size(49, 33);
			switch_FUNC2.Size = size;
			this.SWITCH_FUNC.TabIndex = 12;
			this.SWITCH_FUNC.Text = "Func Repeate";
			this.SWITCH_FUNC.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.SWITCH_FUNC.UseCompatibleTextRendering = true;
			this.SWITCH_FUNC.UseVisualStyleBackColor = false;
			this.Stop_Renamed.BackColor = global::System.Drawing.SystemColors.Control;
			this.Stop_Renamed.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Stop_Renamed.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Stop_Renamed.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control stop_Renamed = this.Stop_Renamed;
			point = new global::System.Drawing.Point(182, 322);
			stop_Renamed.Location = point;
			this.Stop_Renamed.Name = "Stop_Renamed";
			this.Stop_Renamed.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control stop_Renamed2 = this.Stop_Renamed;
			size = new global::System.Drawing.Size(49, 33);
			stop_Renamed2.Size = size;
			this.Stop_Renamed.TabIndex = 11;
			this.Stop_Renamed.Text = "Stop";
			this.Stop_Renamed.UseVisualStyleBackColor = false;
			this.REG_SR.AcceptsReturn = true;
			this.REG_SR.BackColor = global::System.Drawing.Color.Black;
			this.REG_SR.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.REG_SR.Font = new global::System.Drawing.Font("Arial", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.REG_SR.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			global::System.Windows.Forms.Control reg_SR = this.REG_SR;
			point = new global::System.Drawing.Point(205, 124);
			reg_SR.Location = point;
			this.REG_SR.MaxLength = 0;
			this.REG_SR.Name = "REG_SR";
			this.REG_SR.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control reg_SR2 = this.REG_SR;
			size = new global::System.Drawing.Size(41, 35);
			reg_SR2.Size = size;
			this.REG_SR.TabIndex = 10;
			this.REG_SR.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.REG_AU.AcceptsReturn = true;
			this.REG_AU.BackColor = global::System.Drawing.Color.Black;
			this.REG_AU.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.REG_AU.Font = new global::System.Drawing.Font("Arial", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.REG_AU.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			global::System.Windows.Forms.Control reg_AU = this.REG_AU;
			point = new global::System.Drawing.Point(85, 24);
			reg_AU.Location = point;
			this.REG_AU.MaxLength = 0;
			this.REG_AU.Name = "REG_AU";
			this.REG_AU.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control reg_AU2 = this.REG_AU;
			size = new global::System.Drawing.Size(161, 35);
			reg_AU2.Size = size;
			this.REG_AU.TabIndex = 9;
			this.REG_AU.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.REG_ICR.AcceptsReturn = true;
			this.REG_ICR.BackColor = global::System.Drawing.Color.Black;
			this.REG_ICR.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.REG_ICR.Font = new global::System.Drawing.Font("Arial", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.REG_ICR.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			global::System.Windows.Forms.Control reg_ICR = this.REG_ICR;
			point = new global::System.Drawing.Point(88, 124);
			reg_ICR.Location = point;
			this.REG_ICR.MaxLength = 0;
			this.REG_ICR.Name = "REG_ICR";
			this.REG_ICR.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control reg_ICR2 = this.REG_ICR;
			size = new global::System.Drawing.Size(33, 35);
			reg_ICR2.Size = size;
			this.REG_ICR.TabIndex = 8;
			this.REG_ICR.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.REG_PROG.AcceptsReturn = true;
			this.REG_PROG.BackColor = global::System.Drawing.Color.Black;
			this.REG_PROG.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.REG_PROG.Font = new global::System.Drawing.Font("Arial", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.REG_PROG.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			global::System.Windows.Forms.Control reg_PROG = this.REG_PROG;
			point = new global::System.Drawing.Point(91, 262);
			reg_PROG.Location = point;
			this.REG_PROG.MaxLength = 0;
			this.REG_PROG.Name = "REG_PROG";
			this.REG_PROG.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control reg_PROG2 = this.REG_PROG;
			size = new global::System.Drawing.Size(129, 35);
			reg_PROG2.Size = size;
			this.REG_PROG.TabIndex = 7;
			this.REG_PROG.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.REG_AL.AcceptsReturn = true;
			this.REG_AL.BackColor = global::System.Drawing.Color.Black;
			this.REG_AL.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.REG_AL.Font = new global::System.Drawing.Font("Arial", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.REG_AL.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			global::System.Windows.Forms.Control reg_AL = this.REG_AL;
			point = new global::System.Drawing.Point(88, 71);
			reg_AL.Location = point;
			this.REG_AL.MaxLength = 0;
			this.REG_AL.Name = "REG_AL";
			this.REG_AL.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control reg_AL2 = this.REG_AL;
			size = new global::System.Drawing.Size(161, 35);
			reg_AL2.Size = size;
			this.REG_AL.TabIndex = 6;
			this.REG_AL.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.SWITCH_CLEAR.BackColor = global::System.Drawing.SystemColors.Control;
			this.SWITCH_CLEAR.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.SWITCH_CLEAR.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SWITCH_CLEAR.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control switch_CLEAR = this.SWITCH_CLEAR;
			point = new global::System.Drawing.Point(238, 322);
			switch_CLEAR.Location = point;
			this.SWITCH_CLEAR.Name = "SWITCH_CLEAR";
			this.SWITCH_CLEAR.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control switch_CLEAR2 = this.SWITCH_CLEAR;
			size = new global::System.Drawing.Size(49, 33);
			switch_CLEAR2.Size = size;
			this.SWITCH_CLEAR.TabIndex = 5;
			this.SWITCH_CLEAR.Text = "Clear";
			this.SWITCH_CLEAR.UseVisualStyleBackColor = false;
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Black;
			this.Label5.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label5.Font = new global::System.Drawing.Font("Arial", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label3 = this.Label5;
			point = new global::System.Drawing.Point(68, 14);
			label3.Location = point;
			this.Label5.Name = "Label5";
			this.Label5.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control label4 = this.Label5;
			size = new global::System.Drawing.Size(68, 16);
			label4.Size = size;
			this.Label5.TabIndex = 33;
			this.Label5.Text = "S T O P S";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.FII.BackColor = global::System.Drawing.Color.Black;
			this.FII.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.FII.Font = new global::System.Drawing.Font("Times New Roman", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.FII.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control fii = this.FII;
			point = new global::System.Drawing.Point(118, 227);
			fii.Location = point;
			this.FII.Name = "FII";
			this.FII.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control fii2 = this.FII;
			size = new global::System.Drawing.Size(25, 17);
			fii2.Size = size;
			this.FII.TabIndex = 16;
			this.FII.Text = "FII";
			this.FII.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this._Label3_2.AutoSize = true;
			this._Label3_2.BackColor = global::System.Drawing.Color.Black;
			this._Label3_2.Cursor = global::System.Windows.Forms.Cursors.Default;
			this._Label3_2.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this._Label3_2.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label3_ = this._Label3_2;
			point = new global::System.Drawing.Point(80, 201);
			label3_.Location = point;
			this._Label3_2.Name = "_Label3_2";
			this._Label3_2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control label3_2 = this._Label3_2;
			size = new global::System.Drawing.Size(27, 26);
			label3_2.Size = size;
			this._Label3_2.TabIndex = 14;
			this._Label3_2.Text = "F";
			this._Label3_2.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this._Label3_1.AutoSize = true;
			this._Label3_1.BackColor = global::System.Drawing.Color.Black;
			this._Label3_1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this._Label3_1.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this._Label3_1.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label3_3 = this._Label3_1;
			point = new global::System.Drawing.Point(58, 267);
			label3_3.Location = point;
			this._Label3_1.Name = "_Label3_1";
			this._Label3_1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control label3_4 = this._Label3_1;
			size = new global::System.Drawing.Size(27, 26);
			label3_4.Size = size;
			this._Label3_1.TabIndex = 4;
			this._Label3_1.Text = "P";
			this._Label3_1.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Black;
			this.Label4.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label4.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label5 = this.Label4;
			point = new global::System.Drawing.Point(157, 129);
			label5.Location = point;
			this.Label4.Name = "Label4";
			this.Label4.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control label6 = this.Label4;
			size = new global::System.Drawing.Size(42, 26);
			label6.Size = size;
			this.Label4.TabIndex = 3;
			this.Label4.Text = "SR";
			this._Label3_0.AutoSize = true;
			this._Label3_0.BackColor = global::System.Drawing.SystemColors.MenuText;
			this._Label3_0.Cursor = global::System.Windows.Forms.Cursors.Default;
			this._Label3_0.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this._Label3_0.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label3_5 = this._Label3_0;
			point = new global::System.Drawing.Point(19, 129);
			label3_5.Location = point;
			this._Label3_0.Name = "_Label3_0";
			this._Label3_0.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control label3_6 = this._Label3_0;
			size = new global::System.Drawing.Size(55, 26);
			label3_6.Size = size;
			this._Label3_0.TabIndex = 2;
			this._Label3_0.Text = "ICR";
			this._Label3_0.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.SystemColors.ControlText;
			this.Label2.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label2.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label7 = this.Label2;
			point = new global::System.Drawing.Point(23, 76);
			label7.Location = point;
			this.Label2.Name = "Label2";
			this.Label2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control label8 = this.Label2;
			size = new global::System.Drawing.Size(45, 26);
			label8.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "AL";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.SystemColors.WindowText;
			this.Label1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label1.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label9 = this.Label1;
			point = new global::System.Drawing.Point(27, 29);
			label9.Location = point;
			this.Label1.Name = "Label1";
			this.Label1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control label10 = this.Label1;
			size = new global::System.Drawing.Size(46, 26);
			label10.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "AU";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.STOPS.BackColor = global::System.Drawing.Color.Black;
			this.STOPS.Controls.Add(this.STOP4);
			this.STOPS.Controls.Add(this.STOP3);
			this.STOPS.Controls.Add(this.STOP2);
			this.STOPS.Controls.Add(this.STOP1);
			this.STOPS.Controls.Add(this.STOP0);
			this.STOPS.Controls.Add(this.Label5);
			this.STOPS.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.STOPS.ForeColor = global::System.Drawing.SystemColors.WindowText;
			global::System.Windows.Forms.Control stops = this.STOPS;
			point = new global::System.Drawing.Point(41, 441);
			stops.Location = point;
			this.STOPS.Name = "STOPS";
			global::System.Windows.Forms.Control stops2 = this.STOPS;
			padding = new global::System.Windows.Forms.Padding(0);
			stops2.Padding = padding;
			this.STOPS.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control stops3 = this.STOPS;
			size = new global::System.Drawing.Size(208, 66);
			stops3.Size = size;
			this.STOPS.TabIndex = 37;
			this.STOPS.TabStop = false;
			this.STOP4.BackColor = global::System.Drawing.Color.LightGray;
			this.STOP4.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.STOP4.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.STOP4.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control stop = this.STOP4;
			point = new global::System.Drawing.Point(11, 33);
			stop.Location = point;
			this.STOP4.Name = "STOP4";
			this.STOP4.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control stop2 = this.STOP4;
			size = new global::System.Drawing.Size(25, 21);
			stop2.Size = size;
			this.STOP4.TabIndex = 31;
			this.STOP4.Text = "4";
			this.STOP4.UseVisualStyleBackColor = false;
			this.STOP3.BackColor = global::System.Drawing.Color.LightGray;
			this.STOP3.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.STOP3.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.STOP3.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control stop3 = this.STOP3;
			point = new global::System.Drawing.Point(50, 33);
			stop3.Location = point;
			this.STOP3.Name = "STOP3";
			this.STOP3.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control stop4 = this.STOP3;
			size = new global::System.Drawing.Size(25, 21);
			stop4.Size = size;
			this.STOP3.TabIndex = 30;
			this.STOP3.Text = "3";
			this.STOP3.UseVisualStyleBackColor = false;
			this.STOP2.BackColor = global::System.Drawing.Color.LightGray;
			this.STOP2.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.STOP2.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.STOP2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control stop5 = this.STOP2;
			point = new global::System.Drawing.Point(90, 33);
			stop5.Location = point;
			this.STOP2.Name = "STOP2";
			this.STOP2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control stop6 = this.STOP2;
			size = new global::System.Drawing.Size(25, 21);
			stop6.Size = size;
			this.STOP2.TabIndex = 29;
			this.STOP2.Text = "2";
			this.STOP2.UseVisualStyleBackColor = false;
			this.STOP1.BackColor = global::System.Drawing.Color.LightGray;
			this.STOP1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.STOP1.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.STOP1.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control stop7 = this.STOP1;
			point = new global::System.Drawing.Point(130, 33);
			stop7.Location = point;
			this.STOP1.Name = "STOP1";
			this.STOP1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control stop8 = this.STOP1;
			size = new global::System.Drawing.Size(25, 21);
			stop8.Size = size;
			this.STOP1.TabIndex = 28;
			this.STOP1.Text = "1";
			this.STOP1.UseVisualStyleBackColor = false;
			this.STOP0.BackColor = global::System.Drawing.Color.LightGray;
			this.STOP0.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.STOP0.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.STOP0.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control stop9 = this.STOP0;
			point = new global::System.Drawing.Point(167, 33);
			stop9.Location = point;
			this.STOP0.Name = "STOP0";
			this.STOP0.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control stop10 = this.STOP0;
			size = new global::System.Drawing.Size(25, 21);
			stop10.Size = size;
			this.STOP0.TabIndex = 27;
			this.STOP0.Text = "0";
			this.STOP0.UseVisualStyleBackColor = false;
			this.SWITCH_MODE.BackColor = global::System.Drawing.SystemColors.Control;
			this.SWITCH_MODE.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.SWITCH_MODE.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SWITCH_MODE.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control switch_MODE = this.SWITCH_MODE;
			point = new global::System.Drawing.Point(184, 376);
			switch_MODE.Location = point;
			this.SWITCH_MODE.Name = "SWITCH_MODE";
			this.SWITCH_MODE.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control switch_MODE2 = this.SWITCH_MODE;
			size = new global::System.Drawing.Size(49, 33);
			switch_MODE2.Size = size;
			this.SWITCH_MODE.TabIndex = 38;
			this.SWITCH_MODE.Text = "Run";
			this.SWITCH_MODE.UseCompatibleTextRendering = true;
			this.SWITCH_MODE.UseVisualStyleBackColor = false;
			this.Timer1.Enabled = true;
			this.Timer1.Interval = 1000;
			this.Timer2.Enabled = true;
			this.Timer2.Interval = 1;
			this.Label3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control label11 = this.Label3;
			point = new global::System.Drawing.Point(182, 412);
			label11.Location = point;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label12 = this.Label3;
			size = new global::System.Drawing.Size(49, 32);
			label12.Size = size;
			this.Label3.TabIndex = 39;
			this.Label3.Text = "Run  Step";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label3.UseCompatibleTextRendering = true;
			global::System.Windows.Forms.Control ins_SECOND = this.INS_SECOND;
			point = new global::System.Drawing.Point(72, 625);
			ins_SECOND.Location = point;
			this.INS_SECOND.Name = "INS_SECOND";
			global::System.Windows.Forms.Control ins_SECOND2 = this.INS_SECOND;
			size = new global::System.Drawing.Size(121, 20);
			ins_SECOND2.Size = size;
			this.INS_SECOND.TabIndex = 40;
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(6f, 14f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.AutoValidate = global::System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
			this.BackColor = global::System.Drawing.Color.Black;
			size = new global::System.Drawing.Size(299, 616);
			this.ClientSize = size;
			this.Controls.Add(this.INS_SECOND);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.SWITCH_MODE);
			this.Controls.Add(this.STOPS);
			this.Controls.Add(this.BUTTON_LOAD);
			this.Controls.Add(this.Button_DIS_P);
			this.Controls.Add(this.Frame2);
			this.Controls.Add(this.START);
			this.Controls.Add(this.BUTTON_FII);
			this.Controls.Add(this.REG_FUNC);
			this.Controls.Add(this.SWITCH_FUNC);
			this.Controls.Add(this.Stop_Renamed);
			this.Controls.Add(this.REG_SR);
			this.Controls.Add(this.REG_AU);
			this.Controls.Add(this.REG_ICR);
			this.Controls.Add(this.REG_PROG);
			this.Controls.Add(this.REG_AL);
			this.Controls.Add(this.SWITCH_CLEAR);
			this.Controls.Add(this.FII);
			this.Controls.Add(this._Label3_2);
			this.Controls.Add(this._Label3_1);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this._Label3_0);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.Label1);
			this.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Font = new global::System.Drawing.Font("Arial", 8f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ForeColor = global::System.Drawing.Color.Black;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			point = new global::System.Drawing.Point(244, 189);
			this.Location = point;
			this.Name = "Univac1219";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.Text = "UNIVAC 1219 S/N 368";
			this.TopMost = true;
			this.Frame2.ResumeLayout(false);
			this.Frame2.PerformLayout();
			this.STOPS.ResumeLayout(false);
			this.STOPS.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x04000059 RID: 89
		private global::System.ComponentModel.IContainer components;
	}
}
